import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";

import { Theme } from "@radix-ui/themes";
import { Header } from "../components/Header/Header";
import DashBoardMenu from "../components/DashBoardMenu/DashBoard";
const geistSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <DashBoardMenu />
        {children}
      </body>
    </html>
  );
}
