import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import type { ReactNode } from "react";
import DashBoardMenu from "../components/DashBoardMenu/DashBoard";
const geistSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function dashBoardLayout({ children }: { children: ReactNode }) {
  return (
  
      <main className={`${geistSans.variable} antialiased`}>
        <DashBoardMenu />
        {children}
      </main>
   
  );
}