import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { AuthProvider } from "./providers/auth";
import { Header } from "./components/Header/Header";
import { Theme } from "@radix-ui/themes";

const geistSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}
export default function RootLayout({children} : RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <AuthProvider>
          <Header />
          <Theme>{children}</Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
