import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";

import "./globals.css";
import { Header } from "./components/Header/Header";
import { Theme } from "@radix-ui/themes";
const geistSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      		

      <body
        className={`${geistSans.variable} antialiased`}
      >
        <Header />
        		<Theme>
        {children}
             </Theme>
      </body>
 
    </html>
  );
}
